### ISSUE TITLE
Usability - Escape Key

### ISSUE THREAD

**Issue by Pelican104** [pdjstone/archimedes-live#22]
How do we actually send ESCAPE to the emulator? Is there a key combination for this??

Pressing ESCAPE releases the mouse from the emulator rather than sending ESCAPE to the running application in the emulator.

**Comment by pdjstone** [comment]
Pressing Escape does send that key to the emulator - but only once the mouse has already been released. However it is annoying to have to re-click on the window to capture the mouse again each time. The exception is in Chrome, when running fullscreen because it supports the [Keyboard.lock() API](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/lock). So in fullscreen Chrome, Escape does work as expected because you have to press and hold the Escape key to actually leave fullscreen.

I would like to add an alternative keyboard shortcut to send the escape key - perhaps Ctrl-backquote or similar.

**Comment by pdjstone** [comment]
This is now implemented in commit 0b6aa33 - let me know how it works for you.

**Comment by Pelican104** [comment]
That works nicely thanks, I think there was a typo in the commit though with too many IF blocks.

```
function captureKeyShortcuts(event) {
  if (event.altKey && event.keyCode == KEY_F1) {
  if (event.altKey && event.code == 'F1') {
    arc_capture_screenshot();
  } else if (event.ctrlKey && event.code == 'Backquote') {
    console.log('simulate escape');
    setTimeout(() => sendKeyCode(KEY_ESCAPE), 20);
  }
}
```

I edited it on my instance to 

```
function captureKeyShortcuts(event) {
  
  if (event.altKey && event.code == 'F1') {
    arc_capture_screenshot();
  } else if (event.ctrlKey && event.code == 'Backquote') {
    console.log('simulate escape');
    setTimeout(() => sendKeyCode(KEY_ESCAPE), 20);
  }

}
```
That works perfectly and generates the expected escape response in the emulator by using CTRL+`

**Comment by Pelican104** [comment]
Although actually I may have copied the fix from the wrong screen, my bad.
